print('Operadores logicos')
print(True and True)
print(True and False)
print(False and False)
print(True or True)
print(True or False)
print(False or False)
print(not False)
print(not True)
print('=' * 30)
